# Generated by Django 3.0.6 on 2020-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
